-- MySQL Script generated by MySQL Workbench
-- Mon Jun  7 23:52:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema git_it
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema git_it
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `get_it` DEFAULT CHARACTER SET utf8mb4 ;
USE `get_it` ;

-- -----------------------------------------------------
-- Table `git_it`.`producto_canje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `get_it`.`producto_canje` (
  `idregistro` INT(11) NOT NULL AUTO_INCREMENT,
  `idproducto` INT(11) NULL DEFAULT NULL,
  `nombre` VARCHAR(80) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `canjeado` CHAR(2) NULL DEFAULT NULL,
  `producto_canjecol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idregistro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `git_it`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `get_it`.`usuarios` (
  `idusuarios` INT(11) NOT NULL,
  `nombre` VARCHAR(80) NULL DEFAULT NULL,
  `email` VARCHAR(80) NULL DEFAULT NULL,
  `clave` VARCHAR(256) NULL DEFAULT NULL,
  `whatsapp` CHAR(30) NULL DEFAULT NULL,
  `referencia` VARCHAR(80) NULL DEFAULT NULL,
  `estrellas` DECIMAL(5,0) NULL DEFAULT NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
ALTER table usuarios add column `facebook` char(255) null default "No proporcionado" after `whatsapp`;

-- -----------------------------------------------------
-- Table `git_it`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `get_it`.`productos` (
  `idproducto` INT(11) NOT NULL,
  `descripcion` VARCHAR(500) NULL DEFAULT NULL,
  `idusuario` INT(11) NULL DEFAULT NULL,
  `cambiarpor` VARCHAR(500) NULL DEFAULT NULL,
  `canjeadopor` VARCHAR(250) NULL DEFAULT NULL,
  `estado` TINYINT(4) NULL DEFAULT NULL,
  `fecha_publ` DATE NULL DEFAULT NULL,
  `fecha_canje` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` CHAR(2) NULL DEFAULT NULL,
  `categoria` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `fk_idusuario_producto_idx` (`idusuario` ASC),
  CONSTRAINT `fk_idusuario_producto`
    FOREIGN KEY (`idusuario`)
    REFERENCES `git_it`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `get_it`.`usuario_puntage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `get_it`.`usuario_puntaje` (
  `idusuario` INT(11) NOT NULL,
  `idproducto` INT(11) NULL DEFAULT NULL,
  `estrellas` TINYINT(10) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
Alter table usuarios 
